### ISSUE TITLE
Hash collision in Expression caching

### ISSUE THREAD

**Issue by ngedwin98** [mabuchilab/QNET#51]
After caching of `Expression` objects was introduced by closing #26, new `Expression` objects to be created are first checked against `Expression._instances` via a dictionary lookup. However, it turns out there are two often-used expressions with the same hash:
```
a = LocalOperator(hs="0")
hash(-a) == hash(-2*a) # True
```
This seems to occur for any instance `a` of `LocalOperator` (including `Destroy`, etc.), and it also occurs regardless of `a.space`. Changing either of these two things changes the hash, but not the fact that they collide.

A minimal working example of a bug caused by this issue:
```
a-a # 0
a-2*a # 0
```
This is because
```
hash((OperatorPlus, a, -a)) == hash((OperatorPlus, a, -2*a)) # True
```
evaluates as `True`, causing `Expression.create` to construct the wrong expression for `a-2*a`.

A more significant example is
```
import sympy as sp
a = Destroy(hs="1")
SLH([[1]], [sp.sqrt(2)*a], 0).symbolic_heisenberg_eom(a)
```
which produces an incorrect equation of motion for the empty cavity with unit field decay rate, affecting any device model with linear loss (and is closer to how this bug was discovered in the first place).

The straightforward workaround would be setting `Expression.instance_caching = False`, at the expense of losing the caching feature. Any ideas for a fix instead?

**Comment by goerz** [comment]
Wow, that's pretty crazy! Seems like hash collisions in Python happen very easily: https://stackoverflow.com/questions/32504977/hashing-different-tuples-in-python-give-identical-result

I'll look into whether `hashlib` can provide a better alternative.

**Comment by goerz** [comment]
It turns out that the true culprit is defining equality based on the hash:

    def __eq__(self, other):
        return hash(self) == hash(other)

This is *not* a good idea! While equal expression must have the same hash, the reverse is not true (and happens much more frequently than I had thought). Note that things like `dicts` are robust with respect to hash collisions, but *only* if equality is defined correctly.

**Comment by danielwe** [comment]
Yeah, I was surprised by the way you guys talked about hash collisions as a bug. Frequent hash collisions should never result in incorrect behavior, only poor performance. The bug is in what @goerz just quoted, and any other statements that rely on the same assumption.

The contract is that `a == b` is true implies `hash(a) == hash(b)` is also true, _not_ the other way around. For any questions and confusions of this kind, this page in the python documentation is a goldmine: https://docs.python.org/3/reference/datamodel.html

**Comment by ngedwin98** [comment]
Thanks for the clarifications! I didn't mean to imply that the hash collision was a bug itself, but only that real bugs such as `a-a == a-2a` seemed to arise from the hash collision. And as @goerz mentions, it comes from the current implementation of `__eq__` (in `Expression`?), which precisely assumes/enforces `hash(a) == hash(b)` implies `a == b`. I'm glad to hear that Python dictionaries don't rely solely on hash, since this means we could directly compare the `Expression` and its operands instead for equality testing and caching.
