### ISSUE TITLE
series_expand for OperatorPlus doesn't work as intended

### ISSUE THREAD

**Issue by ngedwin98** [mabuchilab/QNET#56]
The following code does not work as intended:
```
k = sympy.symbols("k", positive=True)
a = Destroy(hs="1")
X = 1 + k*a + k**2 a*a
A,B,C = X.series_expand(k,0,2)
```
After this code is run, ```A == X``` and ```B == C == ZeroOperator```. The correct behavior should be ```A == IdentityOperator```, ```B == a```, and ```C == a*a```. In particular, this is causing issues with ```prepare_adiabatic_limit```, producing incorrect expressions for the limit operators.

I'm not sure if this issue also occurs with other subclasses of ```Operator```; I've only tracked it down to ```OperatorPlus``` thus far.

**Comment by danielwe** [comment]
Brief notes while debugging (mainly collecting links to relevant commits):
* The bug seems to originate from ``ScalarTimesOperator._series_expand``, but may also ultimately be due to something in the operator ordering module.
* 95837c0 broke ``ScalarTimesOperator.series_expand``, at least for operators like ``k * a`` and ``k ** 2 * a * a``, raising an AttributeError originating in the operating ordering module, specifically in the instantiation of a ``FullCommutativeHSOrder`` object.
* c0089b4 removed the exception and introduced the current erroneous behavior.
