### ISSUE TITLE
Replace PyX dependency by matplotlib

### ISSUE THREAD

**Issue by ntezak** [mabuchilab/QNET#8]
We should render our circuit diagrams with matplotlib as this dependency is much easier to install and does not require LaTeX to be installed.

**Comment by ntezak** [comment]
@goerz Are you already working on this?

**Comment by goerz** [comment]
I haven't started implementing this, but feel free to assign me to the issue

**Comment by goerz** [comment]
I have started implementing this, using and intermediate representation. Circuits are now translated into a matrix of "tiles". These tiles are then rendered into ascii, a matplotlib diagram, or tikz code. I actually especially like the ascii rendering, which makes it easy to look at diagrams inside of a debugger:

![ascii_circuit](https://cloud.githubusercontent.com/assets/112306/19621112/d2e75b66-9858-11e6-8349-e6c14a55028c.png)

**Comment by ntezak** [comment]
Looks great!

On Oct 22, 2016, at 10:10 AM, Michael Goerz <notifications@github.com<mailto:notifications@github.com>> wrote:

I have started implementing this, using and intermediate representation. Circuits are now translated into a matrix of "tiles". These tiles are then rendered into ascii, a matplotlib diagram, or tikz code. I actually especially like the ascii rendering, which makes it easy to look at diagrams inside of a debugger:

[ascii_circuit]https://cloud.githubusercontent.com/assets/112306/19621112/d2e75b66-9858-11e6-8349-e6c14a55028c.png

##

**Comment by goerz** [comment]
PyX has become considerably more user-friendly (and conda-installable) in the last two years. Thus, we can keep it as a dependency for now. Also, implementing all the existing features in matplotlib turned out to be more difficult than expected.

The ascii-drawing of circuits will be added to v2.0 as a separate feature. We could still move to matplotlib at some point in the future, but I would recommend starting with a matplotlib-based visualization *in parallel* to the PyX based one. Once that matures and has all the features of PyX, we could drop PyX, but this would be in a v3.0 at the earliest.
